import type { TShirt } from '../types';

// Bundled sample stock for DEMO MODE (used only when no backend is reachable —
// e.g. the Netlify-hosted frontend with no API). Photos are stable picsum
// seeds so each piece — and each extra angle — is a distinct, real image.
const img = (seed: string) => `https://picsum.photos/seed/${seed}/600/800`;

export const SAMPLE_ITEMS: TShirt[] = [
  {
    id: 'd-01',
    title: 'Vintage Nike Swoosh',
    description: 'Tee Nike des années 90, coupe oversize, logo brodé.',
    imageUrl: img('fripa-nike-90s'),
    images: [img('fripa-nike-90s-a'), img('fripa-nike-90s-b')],
    price: 28,
    size: 'L',
    brand: 'Nike',
    condition: 'Très bon état',
    color: 'Blanc cassé',
    seller: 'Souk El Jemaa, Tunis',
    category: 'T-shirts',
  },
  {
    id: 'd-02',
    title: 'Sweat Adidas Trefoil',
    description: 'Sweat molleton Adidas, coloris bordeaux. Pièce chinée.',
    imageUrl: img('fripa-adidas-trefoil'),
    images: [img('fripa-adidas-trefoil-a'), img('fripa-adidas-trefoil-b'), img('fripa-adidas-trefoil-c')],
    price: 45,
    salePrice: 35,
    size: 'M',
    brand: 'Adidas',
    condition: 'Comme neuf',
    color: 'Bordeaux',
    seller: 'Fripa Sfax',
    category: 'Sweats',
  },
  {
    id: 'd-03',
    title: 'Polo Lacoste piqué',
    description: 'Polo Lacoste classique, coton piqué, vert sapin.',
    imageUrl: img('fripa-lacoste-polo'),
    price: 38,
    size: 'M',
    brand: 'Lacoste',
    condition: 'Bon état',
    color: 'Vert',
    seller: 'Bab Jedid',
    category: 'Polos',
  },
  {
    id: 'd-04',
    title: 'Veste coupe-vent Kappa',
    description: 'Veste coupe-vent Kappa, coloris rouge. Prête à repartir.',
    imageUrl: img('fripa-kappa-veste'),
    images: [img('fripa-kappa-veste-a'), img('fripa-kappa-veste-b')],
    price: 52,
    size: 'XL',
    brand: 'Kappa',
    condition: 'Bon état',
    color: 'Rouge',
    seller: 'Fripa Menzah',
    category: 'Vestes',
  },
  {
    id: 'd-05',
    title: 'Maillot Italia 2006',
    description: 'Maillot rétro Italie, finale 2006. Collector.',
    imageUrl: img('fripa-italia-2006'),
    price: 60,
    salePrice: 48,
    size: 'L',
    brand: 'Puma',
    condition: 'Vintage',
    color: 'Bleu',
    seller: 'Souk El Jemaa, Tunis',
    category: 'Maillots',
  },
  {
    id: 'd-06',
    title: 'Short cargo Carhartt',
    description: 'Short cargo Carhartt, toile résistante, beige.',
    imageUrl: img('fripa-carhartt-short'),
    price: 34,
    size: 'M',
    brand: 'Carhartt',
    condition: 'Très bon état',
    color: 'Beige',
    seller: 'Fripa Sfax',
    category: 'Shorts',
  },
  {
    id: 'd-07',
    title: 'Jean Levi’s 501',
    description: 'Jean Levi’s 501 brut, coupe droite intemporelle.',
    imageUrl: img('fripa-levis-501'),
    images: [img('fripa-levis-501-a'), img('fripa-levis-501-b')],
    price: 55,
    size: 'L',
    brand: "Levi's",
    condition: 'Bon état',
    color: 'Bleu brut',
    seller: 'Bab Jedid',
    category: 'Jeans',
  },
  {
    id: 'd-08',
    title: 'Tee Champion Reverse',
    description: 'T-shirt Champion, logo script, gris chiné.',
    imageUrl: img('fripa-champion-tee'),
    price: 24,
    size: 'S',
    brand: 'Champion',
    condition: 'Comme neuf',
    color: 'Gris',
    seller: 'Fripa Menzah',
    category: 'T-shirts',
  },
  {
    id: 'd-09',
    title: 'Sweat à capuche Fila',
    description: 'Hoodie Fila color-block, années 90. Épais et douillet.',
    imageUrl: img('fripa-fila-hoodie'),
    price: 42,
    size: 'XL',
    brand: 'Fila',
    condition: 'Très bon état',
    color: 'Marine',
    seller: 'Souk El Jemaa, Tunis',
    category: 'Sweats',
  },
  {
    id: 'd-10',
    title: 'Polo Ralph Lauren',
    description: 'Polo Ralph Lauren, petit poney brodé, bleu ciel.',
    imageUrl: img('fripa-rl-polo'),
    price: 40,
    salePrice: 30,
    size: 'M',
    brand: 'Ralph Lauren',
    condition: 'Comme neuf',
    color: 'Bleu ciel',
    seller: 'Fripa Sfax',
    category: 'Polos',
  },
  {
    id: 'd-11',
    title: 'Veste en jean Wrangler',
    description: 'Veste en jean Wrangler délavée, coupe trucker.',
    imageUrl: img('fripa-wrangler-jacket'),
    images: [img('fripa-wrangler-jacket-a'), img('fripa-wrangler-jacket-b')],
    price: 58,
    size: 'L',
    brand: 'Wrangler',
    condition: 'Vintage',
    color: 'Bleu délavé',
    seller: 'Bab Jedid',
    category: 'Vestes',
  },
  {
    id: 'd-12',
    title: 'Maillot Milan AC',
    description: 'Maillot domicile Milan AC, rayures rouge et noir.',
    imageUrl: img('fripa-milan-jersey'),
    price: 50,
    size: 'M',
    brand: 'Adidas',
    condition: 'Bon état',
    color: 'Rouge/Noir',
    seller: 'Fripa Menzah',
    category: 'Maillots',
  },
  {
    id: 'd-13',
    title: 'Short Nike Dri-Fit',
    description: 'Short de sport Nike Dri-Fit, noir, léger.',
    imageUrl: img('fripa-nike-short'),
    price: 22,
    size: 'S',
    brand: 'Nike',
    condition: 'Comme neuf',
    color: 'Noir',
    seller: 'Souk El Jemaa, Tunis',
    category: 'Shorts',
  },
  {
    id: 'd-14',
    title: 'Jean slim Diesel',
    description: 'Jean Diesel coupe slim, délavage moyen.',
    imageUrl: img('fripa-diesel-jean'),
    price: 48,
    size: 'M',
    brand: 'Diesel',
    condition: 'Très bon état',
    color: 'Bleu',
    seller: 'Fripa Sfax',
    category: 'Jeans',
  },
  {
    id: 'd-15',
    title: 'Tee The North Face',
    description: 'T-shirt The North Face, logo poitrine, olive.',
    imageUrl: img('fripa-tnf-tee'),
    images: [img('fripa-tnf-tee-a'), img('fripa-tnf-tee-b')],
    price: 26,
    salePrice: 20,
    size: 'L',
    brand: 'The North Face',
    condition: 'Bon état',
    color: 'Olive',
    seller: 'Bab Jedid',
    category: 'T-shirts',
  },
  {
    id: 'd-16',
    title: 'Sweat Tommy Hilfiger',
    description: 'Crewneck Tommy Hilfiger, drapeau brodé, crème.',
    imageUrl: img('fripa-tommy-sweat'),
    price: 44,
    size: 'XXL',
    brand: 'Tommy Hilfiger',
    condition: 'Comme neuf',
    color: 'Crème',
    seller: 'Fripa Menzah',
    category: 'Sweats',
  },
  {
    id: 'd-17',
    title: 'Veste Harrington Fred Perry',
    description: 'Veste Harrington Fred Perry, doublure tartan.',
    imageUrl: img('fripa-fredperry-harrington'),
    price: 65,
    size: 'M',
    brand: 'Fred Perry',
    condition: 'Très bon état',
    color: 'Marine',
    seller: 'Souk El Jemaa, Tunis',
    category: 'Vestes',
  },
  {
    id: 'd-18',
    title: 'Polo vintage Sergio Tacchini',
    description: 'Polo Sergio Tacchini rétro, bandes contrastées.',
    imageUrl: img('fripa-sergio-polo'),
    price: 36,
    size: 'L',
    brand: 'Sergio Tacchini',
    condition: 'Vintage',
    color: 'Blanc/Vert',
    seller: 'Fripa Sfax',
    category: 'Polos',
  },
];
