import { TShirt } from './types';

// Placeholder photos via picsum.photos with stable seeds.
// Swap imageUrl values with real product photos when wiring up inventory.
const img = (seed: string) => `https://picsum.photos/seed/${seed}/600/800`;

export const ITEMS: TShirt[] = [
  {
    id: 't-001',
    title: 'Vintage Nike Swoosh',
    description: "Tee Nike des années 90, coupe oversize, logo brodé.",
    imageUrl: img('fripa-nike-90s'),
    price: 28,
    size: 'L',
    brand: 'Nike',
    condition: 'Très bon état',
    color: 'Blanc cassé',
    seller: 'Souk El Jemaa, Tunis',
  },
  {
    id: 't-002',
    title: 'Adidas Trefoil Rouge',
    description: 'Tee-shirt Adidas Originals, coton épais.',
    imageUrl: img('fripa-adidas-trefoil'),
    price: 22,
    size: 'M',
    brand: 'Adidas',
    condition: 'Bon état',
    color: 'Rouge',
    seller: 'Fripa Sfax',
  },
  {
    id: 't-003',
    title: 'Espérance Sportive de Tunis 2004',
    description: "Maillot rétro de l'EST, saison 2003-2004. Pièce rare.",
    imageUrl: img('fripa-est-2004'),
    price: 65,
    size: 'L',
    brand: 'EST',
    condition: 'Vintage',
    color: 'Rouge & Jaune',
    seller: 'Bab El Falla',
  },
  {
    id: 't-004',
    title: 'Harvard University Crew',
    description: 'Tee universitaire ramené des US, coton lourd Champion.',
    imageUrl: img('fripa-harvard'),
    price: 35,
    size: 'M',
    brand: 'Champion',
    condition: 'Comme neuf',
    color: 'Bordeaux',
    seller: 'Fripa La Marsa',
  },
  {
    id: 't-005',
    title: 'Étoile du Sahel 1997',
    description: "Maillot vintage de l'ESS, floqué dans le dos.",
    imageUrl: img('fripa-ess-97'),
    price: 55,
    size: 'L',
    brand: 'ESS',
    condition: 'Vintage',
    color: 'Rouge & Blanc',
    seller: 'Sousse Médina',
  },
  {
    id: 't-006',
    title: 'Carthage Festival 2012',
    description: 'Tee officiel du Festival de Carthage, édition limitée.',
    imageUrl: img('fripa-carthage'),
    price: 18,
    size: 'S',
    brand: 'Local',
    condition: 'Bon état',
    color: 'Noir',
    seller: 'Souk Sidi Bou Saïd',
  },
  {
    id: 't-007',
    title: 'Levi’s Red Tab',
    description: 'Basique Levi’s en coton bio, coupe droite.',
    imageUrl: img('fripa-levis-red'),
    price: 24,
    size: 'M',
    brand: "Levi's",
    condition: 'Comme neuf',
    color: 'Blanc',
    seller: 'Fripa Lac 2',
  },
  {
    id: 't-008',
    title: 'Lakers Kobe #24',
    description: 'Tee NBA Lakers, hommage Kobe Bryant. Imprimé craquelé.',
    imageUrl: img('fripa-lakers-kobe'),
    price: 32,
    size: 'XL',
    brand: 'NBA',
    condition: 'Bon état',
    color: 'Violet',
    seller: 'Fripa Bardo',
  },
  {
    id: 't-009',
    title: 'Tunisie 7 — Hannibal',
    description: 'Tee local imprimé à la main, motif Hannibal Barca.',
    imageUrl: img('fripa-hannibal'),
    price: 30,
    size: 'M',
    brand: 'Tunisie 7',
    condition: 'Comme neuf',
    color: 'Sable',
    seller: 'Tunis Centre Ville',
  },
  {
    id: 't-010',
    title: 'Ralph Lauren Polo Bear',
    description: 'Tee Polo Ralph Lauren, motif ours brodé sur la poitrine.',
    imageUrl: img('fripa-polo-bear'),
    price: 45,
    size: 'L',
    brand: 'Ralph Lauren',
    condition: 'Très bon état',
    color: 'Bleu marine',
    seller: 'Fripa Menzah',
  },
  {
    id: 't-011',
    title: 'Metallica — Master of Puppets',
    description: 'Tee tournée officielle, taille européenne.',
    imageUrl: img('fripa-metallica'),
    price: 38,
    size: 'L',
    brand: 'Metallica',
    condition: 'Vintage',
    color: 'Noir',
    seller: 'Fripa Ariana',
  },
  {
    id: 't-012',
    title: 'Tommy Hilfiger Block Logo',
    description: 'Tommy Jeans, gros logo flag sur la poitrine.',
    imageUrl: img('fripa-tommy-flag'),
    price: 26,
    size: 'M',
    brand: 'Tommy Hilfiger',
    condition: 'Bon état',
    color: 'Bleu',
    seller: 'Fripa Hammamet',
  },
  {
    id: 't-013',
    title: 'Carthage Eagles',
    description: 'Maillot équipe nationale Tunisie 2018, replica.',
    imageUrl: img('fripa-tunisia-2018'),
    price: 40,
    size: 'M',
    brand: 'Uhlsport',
    condition: 'Très bon état',
    color: 'Rouge',
    seller: 'Fripa Manar',
  },
  {
    id: 't-014',
    title: 'Stüssy World Tribe',
    description: 'Tee streetwear Stüssy, imprimé central.',
    imageUrl: img('fripa-stussy'),
    price: 42,
    size: 'L',
    brand: 'Stüssy',
    condition: 'Comme neuf',
    color: 'Crème',
    seller: 'Fripa Berges du Lac',
  },
  {
    id: 't-015',
    title: 'Coca-Cola 1995 Promo',
    description: 'Tee promotionnel Coca-Cola, coton épais USA.',
    imageUrl: img('fripa-coca-95'),
    price: 20,
    size: 'XL',
    brand: 'Coca-Cola',
    condition: 'Vintage',
    color: 'Rouge',
    seller: 'Fripa Kram',
  },
  {
    id: 't-016',
    title: 'Club Africain Rétro',
    description: 'Maillot Club Africain vintage, années 90.',
    imageUrl: img('fripa-ca-retro'),
    price: 58,
    size: 'M',
    brand: 'Club Africain',
    condition: 'Vintage',
    color: 'Rouge & Blanc',
    seller: 'Bab Jedid',
  },
];
